--------------------------------------------------------
--  File created - Sunday-November-11-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACADEMIC_DEGREE
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."ACADEMIC_DEGREE" 
   (	"ACADEMIC_DEGREE_ID" VARCHAR2(20 BYTE), 
	"ACADEMIC_DEGREE" VARCHAR2(20 BYTE), 
	"MAX_LOAD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSES
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."COURSES" 
   (	"COURSE_ID" VARCHAR2(20 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE), 
	"DIVISION_ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(20 BYTE), 
	"LECTURE_HOURS" VARCHAR2(20 BYTE), 
	"SECTION_HOURS" VARCHAR2(20 BYTE), 
	"NUMBER_OF_INSTRUCTORS" VARCHAR2(20 BYTE) DEFAULT 1, 
	"TERM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DAYS
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."DAYS" 
   (	"DAY_ID" VARCHAR2(20 BYTE), 
	"DAY_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."DEPARTMENTS" 
   (	"DEPARTMENT_ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIVISION
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."DIVISION" 
   (	"DIVISION_ID" VARCHAR2(20 BYTE), 
	"GRADE_ID" VARCHAR2(20 BYTE), 
	"NUMBER_OF_STUDENTS" VARCHAR2(20 BYTE), 
	"DIVISION_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRADES
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."GRADES" 
   (	"GRADE_ID" VARCHAR2(20 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRADE_DAYS
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."GRADE_DAYS" 
   (	"GRADE_ID" VARCHAR2(20 BYTE), 
	"DAY_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HALLS
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."HALLS" 
   (	"HALL_ID" VARCHAR2(20 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"CAPACITY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGES
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."PAGES" 
   (	"PAGE_ID" VARCHAR2(20 BYTE), 
	"PAGE_NAME" VARCHAR2(20 BYTE), 
	"ROLE_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERIODS
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."PERIODS" 
   (	"PERIOD_ID" VARCHAR2(20 BYTE), 
	"DAY_ID" VARCHAR2(20 BYTE), 
	"PERIOD_NAME" VARCHAR2(20 BYTE), 
	"START_TIME" VARCHAR2(20 BYTE), 
	"END_TIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREFERENCES
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."PREFERENCES" 
   (	"PREFERENCE_ID" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"COURSE_ID" VARCHAR2(20 BYTE), 
	"PERIOD_ID" VARCHAR2(20 BYTE), 
	"RANK" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESULT
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."RESULT" 
   (	"RESULT_ID" VARCHAR2(20 BYTE), 
	"PREFERENCE_ID" VARCHAR2(20 BYTE), 
	"HALL_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."ROLES" 
   (	"ROLE_ID" VARCHAR2(20 BYTE), 
	"ROLE_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SCHEDULE"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"FULL_NAME" VARCHAR2(20 BYTE), 
	"DATE_OF_EMPLOYMENT" DATE, 
	"ACADEMIC_FIELD" VARCHAR2(20 BYTE), 
	"ROLE_ID" VARCHAR2(20 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(20 BYTE), 
	"ACADEMIC_DEGREE_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCHEDULE.ACADEMIC_DEGREE
SET DEFINE OFF;
REM INSERTING into SCHEDULE.COURSES
SET DEFINE OFF;
REM INSERTING into SCHEDULE.DAYS
SET DEFINE OFF;
REM INSERTING into SCHEDULE.DEPARTMENTS
SET DEFINE OFF;
REM INSERTING into SCHEDULE.DIVISION
SET DEFINE OFF;
REM INSERTING into SCHEDULE.GRADES
SET DEFINE OFF;
REM INSERTING into SCHEDULE.GRADE_DAYS
SET DEFINE OFF;
REM INSERTING into SCHEDULE.HALLS
SET DEFINE OFF;
REM INSERTING into SCHEDULE.PAGES
SET DEFINE OFF;
REM INSERTING into SCHEDULE.PERIODS
SET DEFINE OFF;
REM INSERTING into SCHEDULE.PREFERENCES
SET DEFINE OFF;
REM INSERTING into SCHEDULE.RESULT
SET DEFINE OFF;
REM INSERTING into SCHEDULE.ROLES
SET DEFINE OFF;
REM INSERTING into SCHEDULE.USERS
SET DEFINE OFF;
